# Generated by Django 2.2.3 on 2019-08-05 13:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Unique code for system')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('docs_url', models.URLField(verbose_name='Url for documentation description')),
                ('prefixes', jsonfield.fields.JSONField(blank=True, default=dict, help_text='Example: {"": "uploads-public", "api_key": "uploads"}. If security parameters contain "api_key", the prefix /uploads will be used, otherwise /uploads-public')),
                ('security_overrides', jsonfield.fields.JSONField(blank=True, default=dict, help_text='Substitution for security definition. For example, {"api_key": {"type": "apiKey", "name": "x-kong-api", "in": "header"}}')),
                ('json_data', jsonfield.fields.JSONField(default=dict)),
                ('last_update', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
