# Generated by Django 2.2.4 on 2019-08-20 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_uri', models.URLField(verbose_name='Redirect url')),
                ('status', models.CharField(choices=[('review', 'review'), ('accepted', 'accepted'), ('declined', 'declined')], default='review', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Request initiator')),
            ],
        ),
    ]
