# Generated by Django 2.2.4 on 2019-08-27 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregator', '0003_kongtokenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregistrationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
